###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################

SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3f3fc6ad-ec33-4644-a809-efe11adf4329/0ce2b8a29ccc643077b90ea9c37896ba/aspnetcore-runtime-6.0.0-preview.3.21201.13-linux-arm.tar.gz"

SRC_URI[md5sum] = "11708B6E14182F0CA06064798E845125"
SRC_URI[sha256sum] = "0B89A86243EBAAC449EF8E426AA7407C07A55810F4ACA0C8CDFB605108648C78"

