###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/57235015-0fcd-4785-a550-8fce2b489f81/303184bd837591ec206d06dc64284c3b/aspnetcore-runtime-6.0.0-preview.3.21201.13-linux-x64.tar.gz"

SRC_URI[md5sum] = "0F26E196CFCDE6C2734026713B8F2FF8"
SRC_URI[sha256sum] = "647773546875B9827F14A90520C73EB2B80AACD6F072356FA52DE1BEC8E8C4A5"
