###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f5171161-ffd4-4649-9076-e3a20b6543e4/f9b1a9eec1cfd642266c73da656da1d7/aspnetcore-runtime-6.0.0-preview.3.21201.13-linux-arm64.tar.gz"

SRC_URI[md5sum] = "DFD820DD7B57791A23E48E422EDEB38D"
SRC_URI[sha256sum] = "A4478AD01600CE2DE84B106E86A7FE7B735A8B171E35A18C1574A99D5B2F0770"
