###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/57235015-0fcd-4785-a550-8fce2b489f81/303184bd837591ec206d06dc64284c3b/aspnetcore-runtime-6.0.0-preview.3.21201.13-linux-x64.tar.gz"

SRC_URI[md5sum] = "0f26e196cfcde6c2734026713b8f2ff8"
SRC_URI[sha256sum] = "647773546875b9827f14a90520c73eb2b80aacd6f072356fa52de1bec8e8c4a5"
