###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/38227134-51b6-4275-bfa2-2c21ae2759d1/e8efe313494b4566762ea81f9d6c8495/dotnet-runtime-6.0.0-preview.3.21201.4-linux-arm.tar.gz"

SRC_URI[md5sum] = "130190A2E7B5BADC3B6400BFF0EF7621"
SRC_URI[sha256sum] = "360121F6E5611CA9E82D3C975A132FC5C2B0FB4700387532403D6ECF7E9C8D20"
