###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/cbbc6b7c-d7c2-485b-a706-9e047a3f1eac/b194be59ddfd95cbc67d81a12b7753db/dotnet-runtime-6.0.0-preview.3.21201.4-linux-arm64.tar.gz"

SRC_URI[md5sum] = "97540BDCB49648A20136E4DAA4A6A2D2"
SRC_URI[sha256sum] = "DAA1A4E3F183A1F1A3EBB97DF1CC73B55B32CBDB5B04F62497BBFDEC3520D414"

