###################################################################################################
# Contains the URL and checksums to download version 6.0.0-preview.3 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/cbbc6b7c-d7c2-485b-a706-9e047a3f1eac/b194be59ddfd95cbc67d81a12b7753db/dotnet-runtime-6.0.0-preview.3.21201.4-linux-arm64.tar.gz"

SRC_URI[md5sum] = "97540bdcb49648a20136e4daa4a6a2d2"
SRC_URI[sha256sum] = "daa1a4e3f183a1f1a3ebb97df1cc73b55b32cbdb5b04f62497bbfdec3520d414"

DOTNET_CORE_VERSION = "6.0.0-preview.3.21201.4"