###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/dcd635a9-6caf-4958-b3df-01e1c204ca1e/b201804d05de9573a8b454bccac56482/dotnet-runtime-6.0.0-linux-arm.tar.gz"

SRC_URI[sha512sum] = "575037f2e164deaf3bcdd82f7b3f2b5a5784547c5bad4070375c00373722265401b88a81695b919f92ca176f21c1bdf1716f8fce16ab3d301ae666daa8cae750"

DOTNET_CORE_VERSION = "6.0.0"