###################################################################################################
# Contains the URL and checksums to download version 6.0.0-preview.3 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/38227134-51b6-4275-bfa2-2c21ae2759d1/e8efe313494b4566762ea81f9d6c8495/dotnet-runtime-6.0.0-preview.3.21201.4-linux-arm.tar.gz"

SRC_URI[md5sum] = "130190a2e7b5badc3b6400bff0ef7621"
SRC_URI[sha256sum] = "360121f6e5611ca9e82d3c975a132fc5c2b0fb4700387532403d6ecf7e9c8d20"

DOTNET_CORE_VERSION = "6.0.0-preview.3.21201.4"