###################################################################################################
# Contains the URL and checksums to download version 6.0.0-preview.3 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/08d83899-a68e-486f-9dd6-b775bac12612/dd60b334b54191ba2b3821dc608a20af/dotnet-runtime-6.0.0-preview.3.21201.4-linux-x64.tar.gz"

SRC_URI[md5sum] = "1cbd544bc1f7a0b213a7cea5bb87cb5e"
SRC_URI[sha256sum] = "cd0688abbf2f9abecc7de4a95b5b585a0640aa1e3d1521d6fa8587bec249a5b9"

DOTNET_CORE_VERSION = "6.0.0-preview.3.21201.4"