###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/08d83899-a68e-486f-9dd6-b775bac12612/dd60b334b54191ba2b3821dc608a20af/dotnet-runtime-6.0.0-preview.3.21201.4-linux-x64.tar.gz"

SRC_URI[md5sum] = "1CBD544BC1F7A0B213A7CEA5BB87CB5E"
SRC_URI[sha256sum] = "CD0688ABBF2F9ABECC7DE4A95B5B585A0640AA1E3D1521D6FA8587BEC249A5B9"
